#!/usr/bin/env bash
# vim: ft=sh
#
# bootstrap installs things.
# https://github.com/holman/dotfiles

# NOTE: returning 0 == True, returning 1 == False

UPDATE_PACMAN=
POSITIONAL=()
while [[ "$#" -gt 0 ]]; do
  key="$1"
  case $key in
    -u|--update)
      UPDATE_PACMAN=1
      shift
    ;;
    *)
      POSITIONAL+=("$1")
      shift
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$XDG_CONFIG_HOME"]; then
  export XDG_CONFIG_HOME="$HOME/.config"
fi

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

# Make sure a log directory exists.
if [ ! -d "$DOTFILES_ROOT/logs" ]; then
  mkdir "$DOTFILES_ROOT"/logs
fi
# Find the name for the next log file.
logFile="$DOTFILES_ROOT/logs/log"
i="1"
while [ -e "$logFile" ]
do
  logFile="$DOTFILES_ROOT/logs/log$i"
  i=$[$i+1]
done
touch "$logFile"

set -e

echo ''

install_pacman() {
  # If we're on a Mac, let's install and setup homebrew.
  if isOSX
  then
    if ! hasCommand brew; then
      info "installing Mac dependencies"
      if source os/mac.sh >/tmp/dotfiles-dot 2>&1
      then
        success "dependencies installed"
      else
        fail "error installing dependencies"
      fi
    fi
  # If we're on linux, let's update apt-get
  elif isLinux
  then
    info "installing Linux dependencies"
    if source os/linux.sh
    then
      success "dependencies installed"
    else
      fail "error installing dependencies"
    fi
  fi
}

source "$DOTFILES_ROOT"/script/utils.sh
if [ -n "$UPDATE_PACMAN" ]; then
  install_pacman
fi
source "$DOTFILES_ROOT"/script/link_dots
# source "$DOTFILES_ROOT"/script/install
# source "$DOTFILES_ROOT"/script/postinstall


echo ''
echo '  All installed!'
