#!/usr/bin/env bash
#
# Run all dotfiles installers.
# https://github.com/holman/dotfiles

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name 'postinstall.sh')
do
echo $src
  source $src
done
